# Generated by Django 5.1.6 on 2025-02-16 20:36

import djrichtextfield.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='bio',
            field=djrichtextfield.models.RichTextField(blank=True, max_length=300, null=True),
        ),
    ]
